// Generated automatically by nearley, version 2.20.1
// http://github.com/Hardmath123/nearley
(function () {
function id(x) { return x[0]; }
var grammar = {
    Lexer: undefined,
    ParserRules: [
    {"name": "programa$ebnf$1", "symbols": ["sentencia"]},
    {"name": "programa$ebnf$1", "symbols": ["programa$ebnf$1", "sentencia"], "postprocess": function arrpush(d) {return d[0].concat([d[1]]);}},
    {"name": "programa", "symbols": ["programa$ebnf$1"]},
    {"name": "sentencia$ebnf$1", "symbols": []},
    {"name": "sentencia$ebnf$1", "symbols": ["sentencia$ebnf$1", "NLINEA"], "postprocess": function arrpush(d) {return d[0].concat([d[1]]);}},
    {"name": "sentencia$ebnf$2", "symbols": ["TAB"], "postprocess": id},
    {"name": "sentencia$ebnf$2", "symbols": [], "postprocess": function(d) {return null;}},
    {"name": "sentencia", "symbols": ["declaracion_variable", "sentencia$ebnf$1", "sentencia$ebnf$2"]},
    {"name": "sentencia$ebnf$3", "symbols": []},
    {"name": "sentencia$ebnf$3", "symbols": ["sentencia$ebnf$3", "NLINEA"], "postprocess": function arrpush(d) {return d[0].concat([d[1]]);}},
    {"name": "sentencia$ebnf$4", "symbols": ["TAB"], "postprocess": id},
    {"name": "sentencia$ebnf$4", "symbols": [], "postprocess": function(d) {return null;}},
    {"name": "sentencia", "symbols": ["declaracion_sentencia", "sentencia$ebnf$3", "sentencia$ebnf$4"]},
    {"name": "sentencia$ebnf$5", "symbols": []},
    {"name": "sentencia$ebnf$5", "symbols": ["sentencia$ebnf$5", "NLINEA"], "postprocess": function arrpush(d) {return d[0].concat([d[1]]);}},
    {"name": "sentencia$ebnf$6", "symbols": ["TAB"], "postprocess": id},
    {"name": "sentencia$ebnf$6", "symbols": [], "postprocess": function(d) {return null;}},
    {"name": "sentencia", "symbols": ["declaracion_funcion", "sentencia$ebnf$5", "sentencia$ebnf$6"]},
    {"name": "sentencia$ebnf$7", "symbols": []},
    {"name": "sentencia$ebnf$7", "symbols": ["sentencia$ebnf$7", "NLINEA"], "postprocess": function arrpush(d) {return d[0].concat([d[1]]);}},
    {"name": "sentencia$ebnf$8", "symbols": ["TAB"], "postprocess": id},
    {"name": "sentencia$ebnf$8", "symbols": [], "postprocess": function(d) {return null;}},
    {"name": "sentencia", "symbols": ["declaracion_condicional", "sentencia$ebnf$7", "sentencia$ebnf$8"]},
    {"name": "sentencia$ebnf$9", "symbols": []},
    {"name": "sentencia$ebnf$9", "symbols": ["sentencia$ebnf$9", "NLINEA"], "postprocess": function arrpush(d) {return d[0].concat([d[1]]);}},
    {"name": "sentencia$ebnf$10", "symbols": ["TAB"], "postprocess": id},
    {"name": "sentencia$ebnf$10", "symbols": [], "postprocess": function(d) {return null;}},
    {"name": "sentencia", "symbols": ["declaracion_ciclica", "sentencia$ebnf$9", "sentencia$ebnf$10"]},
    {"name": "declaracion_funcion$ebnf$1", "symbols": ["NLINEA"], "postprocess": id},
    {"name": "declaracion_funcion$ebnf$1", "symbols": [], "postprocess": function(d) {return null;}},
    {"name": "declaracion_funcion$ebnf$2", "symbols": ["contenido_funcion"]},
    {"name": "declaracion_funcion$ebnf$2", "symbols": ["declaracion_funcion$ebnf$2", "contenido_funcion"], "postprocess": function arrpush(d) {return d[0].concat([d[1]]);}},
    {"name": "declaracion_funcion", "symbols": ["FUNCTION", "ESP", "funcion", "ESP", "ALLAVE", "declaracion_funcion$ebnf$1", "declaracion_funcion$ebnf$2", "CLLAVE"]},
    {"name": "declaracion_funcion$string$1", "symbols": [{"literal":"="}, {"literal":">"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "declaracion_funcion$ebnf$3", "symbols": ["NLINEA"], "postprocess": id},
    {"name": "declaracion_funcion$ebnf$3", "symbols": [], "postprocess": function(d) {return null;}},
    {"name": "declaracion_funcion$ebnf$4", "symbols": ["contenido_funcion"]},
    {"name": "declaracion_funcion$ebnf$4", "symbols": ["declaracion_funcion$ebnf$4", "contenido_funcion"], "postprocess": function arrpush(d) {return d[0].concat([d[1]]);}},
    {"name": "declaracion_funcion", "symbols": ["APAREN", "parametros", "CPAREN", "ESP", "declaracion_funcion$string$1", "ESP", "ALLAVE", "declaracion_funcion$ebnf$3", "declaracion_funcion$ebnf$4", "CLLAVE"]},
    {"name": "contenido_funcion$ebnf$1", "symbols": ["TAB"], "postprocess": id},
    {"name": "contenido_funcion$ebnf$1", "symbols": [], "postprocess": function(d) {return null;}},
    {"name": "contenido_funcion$ebnf$2", "symbols": []},
    {"name": "contenido_funcion$ebnf$2", "symbols": ["contenido_funcion$ebnf$2", "NLINEA"], "postprocess": function arrpush(d) {return d[0].concat([d[1]]);}},
    {"name": "contenido_funcion", "symbols": ["contenido_funcion$ebnf$1", "declaracion_variable", "contenido_funcion$ebnf$2"]},
    {"name": "contenido_funcion$ebnf$3", "symbols": ["TAB"], "postprocess": id},
    {"name": "contenido_funcion$ebnf$3", "symbols": [], "postprocess": function(d) {return null;}},
    {"name": "contenido_funcion$ebnf$4", "symbols": []},
    {"name": "contenido_funcion$ebnf$4", "symbols": ["contenido_funcion$ebnf$4", "NLINEA"], "postprocess": function arrpush(d) {return d[0].concat([d[1]]);}},
    {"name": "contenido_funcion", "symbols": ["contenido_funcion$ebnf$3", "declaracion_sentencia", "contenido_funcion$ebnf$4"]},
    {"name": "contenido_funcion$ebnf$5", "symbols": ["TAB"], "postprocess": id},
    {"name": "contenido_funcion$ebnf$5", "symbols": [], "postprocess": function(d) {return null;}},
    {"name": "contenido_funcion$ebnf$6", "symbols": []},
    {"name": "contenido_funcion$ebnf$6", "symbols": ["contenido_funcion$ebnf$6", "NLINEA"], "postprocess": function arrpush(d) {return d[0].concat([d[1]]);}},
    {"name": "contenido_funcion", "symbols": ["contenido_funcion$ebnf$5", "declaracion_condicional", "contenido_funcion$ebnf$6"]},
    {"name": "contenido_funcion$ebnf$7", "symbols": ["TAB"], "postprocess": id},
    {"name": "contenido_funcion$ebnf$7", "symbols": [], "postprocess": function(d) {return null;}},
    {"name": "contenido_funcion$ebnf$8", "symbols": []},
    {"name": "contenido_funcion$ebnf$8", "symbols": ["contenido_funcion$ebnf$8", "NLINEA"], "postprocess": function arrpush(d) {return d[0].concat([d[1]]);}},
    {"name": "contenido_funcion", "symbols": ["contenido_funcion$ebnf$7", "declaracion_ciclica", "contenido_funcion$ebnf$8"]},
    {"name": "declaracion_ciclica$ebnf$1", "symbols": ["NLINEA"], "postprocess": id},
    {"name": "declaracion_ciclica$ebnf$1", "symbols": [], "postprocess": function(d) {return null;}},
    {"name": "declaracion_ciclica$ebnf$2", "symbols": ["contenido_cic"]},
    {"name": "declaracion_ciclica$ebnf$2", "symbols": ["declaracion_ciclica$ebnf$2", "contenido_cic"], "postprocess": function arrpush(d) {return d[0].concat([d[1]]);}},
    {"name": "declaracion_ciclica$ebnf$3", "symbols": ["TAB"], "postprocess": id},
    {"name": "declaracion_ciclica$ebnf$3", "symbols": [], "postprocess": function(d) {return null;}},
    {"name": "declaracion_ciclica", "symbols": ["FOR", "ESP", "APAREN", "parametros_ciclica", "CPAREN", "ESP", "ALLAVE", "declaracion_ciclica$ebnf$1", "declaracion_ciclica$ebnf$2", "declaracion_ciclica$ebnf$3", "CLLAVE"]},
    {"name": "parametros_ciclica", "symbols": ["declaracion_variable", "ESP", "IDENTIFICADOR", "ESP", "COPERADOR", "ESP", "term", "PCOMA", "ESP", "IDENTIFICADOR", "ESP", "IGUAL", "ESP", "operacion"]},
    {"name": "parametros_ciclica", "symbols": ["IDENTIFICADOR", "PCOMA", "ESP", "IDENTIFICADOR", "ESP", "COPERADOR", "ESP", "NUMERO", "PCOMA", "ESP", "IDENTIFICADOR", "ESP", "IGUAL", "ESP", "operacion"]},
    {"name": "contenido_cic$ebnf$1", "symbols": ["TAB"], "postprocess": id},
    {"name": "contenido_cic$ebnf$1", "symbols": [], "postprocess": function(d) {return null;}},
    {"name": "contenido_cic$ebnf$2", "symbols": []},
    {"name": "contenido_cic$ebnf$2", "symbols": ["contenido_cic$ebnf$2", "NLINEA"], "postprocess": function arrpush(d) {return d[0].concat([d[1]]);}},
    {"name": "contenido_cic", "symbols": ["contenido_cic$ebnf$1", "declaracion_variable", "contenido_cic$ebnf$2"]},
    {"name": "contenido_cic$ebnf$3", "symbols": ["TAB"], "postprocess": id},
    {"name": "contenido_cic$ebnf$3", "symbols": [], "postprocess": function(d) {return null;}},
    {"name": "contenido_cic$ebnf$4", "symbols": []},
    {"name": "contenido_cic$ebnf$4", "symbols": ["contenido_cic$ebnf$4", "NLINEA"], "postprocess": function arrpush(d) {return d[0].concat([d[1]]);}},
    {"name": "contenido_cic", "symbols": ["contenido_cic$ebnf$3", "declaracion_sentencia", "contenido_cic$ebnf$4"]},
    {"name": "contenido_cic$ebnf$5", "symbols": ["TAB"], "postprocess": id},
    {"name": "contenido_cic$ebnf$5", "symbols": [], "postprocess": function(d) {return null;}},
    {"name": "contenido_cic$ebnf$6", "symbols": []},
    {"name": "contenido_cic$ebnf$6", "symbols": ["contenido_cic$ebnf$6", "NLINEA"], "postprocess": function arrpush(d) {return d[0].concat([d[1]]);}},
    {"name": "contenido_cic", "symbols": ["contenido_cic$ebnf$5", "declaracion_condicional", "contenido_cic$ebnf$6"]},
    {"name": "declaracion_condicional$ebnf$1", "symbols": ["NLINEA"], "postprocess": id},
    {"name": "declaracion_condicional$ebnf$1", "symbols": [], "postprocess": function(d) {return null;}},
    {"name": "declaracion_condicional$ebnf$2", "symbols": ["contenido_cond"]},
    {"name": "declaracion_condicional$ebnf$2", "symbols": ["declaracion_condicional$ebnf$2", "contenido_cond"], "postprocess": function arrpush(d) {return d[0].concat([d[1]]);}},
    {"name": "declaracion_condicional$ebnf$3", "symbols": ["TAB"], "postprocess": id},
    {"name": "declaracion_condicional$ebnf$3", "symbols": [], "postprocess": function(d) {return null;}},
    {"name": "declaracion_condicional$ebnf$4$subexpression$1$ebnf$1", "symbols": ["NLINEA"], "postprocess": id},
    {"name": "declaracion_condicional$ebnf$4$subexpression$1$ebnf$1", "symbols": [], "postprocess": function(d) {return null;}},
    {"name": "declaracion_condicional$ebnf$4$subexpression$1$ebnf$2", "symbols": ["contenido_cond"]},
    {"name": "declaracion_condicional$ebnf$4$subexpression$1$ebnf$2", "symbols": ["declaracion_condicional$ebnf$4$subexpression$1$ebnf$2", "contenido_cond"], "postprocess": function arrpush(d) {return d[0].concat([d[1]]);}},
    {"name": "declaracion_condicional$ebnf$4$subexpression$1$ebnf$3", "symbols": ["TAB"], "postprocess": id},
    {"name": "declaracion_condicional$ebnf$4$subexpression$1$ebnf$3", "symbols": [], "postprocess": function(d) {return null;}},
    {"name": "declaracion_condicional$ebnf$4$subexpression$1", "symbols": ["ESP", "ELSE", "ESP", "ALLAVE", "declaracion_condicional$ebnf$4$subexpression$1$ebnf$1", "declaracion_condicional$ebnf$4$subexpression$1$ebnf$2", "declaracion_condicional$ebnf$4$subexpression$1$ebnf$3", "CLLAVE"]},
    {"name": "declaracion_condicional$ebnf$4", "symbols": ["declaracion_condicional$ebnf$4$subexpression$1"], "postprocess": id},
    {"name": "declaracion_condicional$ebnf$4", "symbols": [], "postprocess": function(d) {return null;}},
    {"name": "declaracion_condicional", "symbols": ["IF", "ESP", "APAREN", "parametros_condicional", "CPAREN", "ESP", "ALLAVE", "declaracion_condicional$ebnf$1", "declaracion_condicional$ebnf$2", "declaracion_condicional$ebnf$3", "CLLAVE", "declaracion_condicional$ebnf$4"]},
    {"name": "parametros_condicional", "symbols": ["BOOLEANO"]},
    {"name": "parametros_condicional$ebnf$1", "symbols": []},
    {"name": "parametros_condicional$ebnf$1$subexpression$1", "symbols": ["ESP", "LOPERADOR", "ESP", "term", "ESP", "COPERADOR", "ESP", "term"]},
    {"name": "parametros_condicional$ebnf$1", "symbols": ["parametros_condicional$ebnf$1", "parametros_condicional$ebnf$1$subexpression$1"], "postprocess": function arrpush(d) {return d[0].concat([d[1]]);}},
    {"name": "parametros_condicional", "symbols": ["term", "ESP", "COPERADOR", "ESP", "term", "parametros_condicional$ebnf$1"]},
    {"name": "contenido_cond$ebnf$1", "symbols": ["TAB"], "postprocess": id},
    {"name": "contenido_cond$ebnf$1", "symbols": [], "postprocess": function(d) {return null;}},
    {"name": "contenido_cond$ebnf$2", "symbols": []},
    {"name": "contenido_cond$ebnf$2", "symbols": ["contenido_cond$ebnf$2", "NLINEA"], "postprocess": function arrpush(d) {return d[0].concat([d[1]]);}},
    {"name": "contenido_cond", "symbols": ["contenido_cond$ebnf$1", "declaracion_variable", "contenido_cond$ebnf$2"]},
    {"name": "contenido_cond$ebnf$3", "symbols": ["TAB"], "postprocess": id},
    {"name": "contenido_cond$ebnf$3", "symbols": [], "postprocess": function(d) {return null;}},
    {"name": "contenido_cond$ebnf$4", "symbols": []},
    {"name": "contenido_cond$ebnf$4", "symbols": ["contenido_cond$ebnf$4", "NLINEA"], "postprocess": function arrpush(d) {return d[0].concat([d[1]]);}},
    {"name": "contenido_cond", "symbols": ["contenido_cond$ebnf$3", "declaracion_sentencia", "contenido_cond$ebnf$4"]},
    {"name": "declaracion_sentencia", "symbols": ["funcion", "PCOMA"]},
    {"name": "declaracion_sentencia", "symbols": ["objeto", "IDENTIFICADOR", "PCOMA"]},
    {"name": "declaracion_sentencia", "symbols": ["objeto", "funcion", "PCOMA"]},
    {"name": "declaracion_variable", "symbols": ["VAR", "ESP", "IDENTIFICADOR", "ESP", "IGUAL", "ESP", "term", "PCOMA"]},
    {"name": "declaracion_variable", "symbols": ["LET", "ESP", "IDENTIFICADOR", "ESP", "IGUAL", "ESP", "term", "PCOMA"]},
    {"name": "declaracion_variable", "symbols": ["CONST", "ESP", "IDENTIFICADOR", "ESP", "IGUAL", "ESP", "term", "PCOMA"]},
    {"name": "objeto$ebnf$1$subexpression$1", "symbols": ["IDENTIFICADOR", "PUNTO"]},
    {"name": "objeto$ebnf$1", "symbols": ["objeto$ebnf$1$subexpression$1"]},
    {"name": "objeto$ebnf$1$subexpression$2", "symbols": ["IDENTIFICADOR", "PUNTO"]},
    {"name": "objeto$ebnf$1", "symbols": ["objeto$ebnf$1", "objeto$ebnf$1$subexpression$2"], "postprocess": function arrpush(d) {return d[0].concat([d[1]]);}},
    {"name": "objeto", "symbols": ["objeto$ebnf$1"]},
    {"name": "funcion", "symbols": ["IDENTIFICADOR", "APAREN", "parametros", "CPAREN"]},
    {"name": "parametros$ebnf$1$subexpression$1$ebnf$1", "symbols": []},
    {"name": "parametros$ebnf$1$subexpression$1$ebnf$1$subexpression$1", "symbols": ["COMA", "ESP", "term"]},
    {"name": "parametros$ebnf$1$subexpression$1$ebnf$1", "symbols": ["parametros$ebnf$1$subexpression$1$ebnf$1", "parametros$ebnf$1$subexpression$1$ebnf$1$subexpression$1"], "postprocess": function arrpush(d) {return d[0].concat([d[1]]);}},
    {"name": "parametros$ebnf$1$subexpression$1", "symbols": ["term", "parametros$ebnf$1$subexpression$1$ebnf$1"]},
    {"name": "parametros$ebnf$1", "symbols": ["parametros$ebnf$1$subexpression$1"], "postprocess": id},
    {"name": "parametros$ebnf$1", "symbols": [], "postprocess": function(d) {return null;}},
    {"name": "parametros", "symbols": ["parametros$ebnf$1"]},
    {"name": "operacion$ebnf$1", "symbols": []},
    {"name": "operacion$ebnf$1$subexpression$1", "symbols": ["ESP", "OPERADOR", "ESP", "term"]},
    {"name": "operacion$ebnf$1", "symbols": ["operacion$ebnf$1", "operacion$ebnf$1$subexpression$1"], "postprocess": function arrpush(d) {return d[0].concat([d[1]]);}},
    {"name": "operacion", "symbols": ["term", "ESP", "OPERADOR", "ESP", "term", "operacion$ebnf$1"]},
    {"name": "term", "symbols": ["IDENTIFICADOR"]},
    {"name": "term", "symbols": ["NUMERO"]},
    {"name": "term", "symbols": ["STRING"]},
    {"name": "term", "symbols": ["BOOLEANO"]},
    {"name": "TAB$ebnf$1", "symbols": ["ESP"]},
    {"name": "TAB$ebnf$1", "symbols": ["TAB$ebnf$1", "ESP"], "postprocess": function arrpush(d) {return d[0].concat([d[1]]);}},
    {"name": "TAB", "symbols": ["ESP", "TAB$ebnf$1"]},
    {"name": "NLINEA$ebnf$1", "symbols": []},
    {"name": "NLINEA$ebnf$1", "symbols": ["NLINEA$ebnf$1", "ESP"], "postprocess": function arrpush(d) {return d[0].concat([d[1]]);}},
    {"name": "NLINEA", "symbols": ["NLINEA$ebnf$1", {"literal":"\n"}]},
    {"name": "ESP", "symbols": [{"literal":" "}]},
    {"name": "IDENTIFICADOR", "symbols": ["lenguaje"]},
    {"name": "IDENTIFICADOR$ebnf$1$subexpression$1", "symbols": ["lenguaje", "NUMERO"]},
    {"name": "IDENTIFICADOR$ebnf$1", "symbols": ["IDENTIFICADOR$ebnf$1$subexpression$1"]},
    {"name": "IDENTIFICADOR$ebnf$1$subexpression$2", "symbols": ["lenguaje", "NUMERO"]},
    {"name": "IDENTIFICADOR$ebnf$1", "symbols": ["IDENTIFICADOR$ebnf$1", "IDENTIFICADOR$ebnf$1$subexpression$2"], "postprocess": function arrpush(d) {return d[0].concat([d[1]]);}},
    {"name": "IDENTIFICADOR", "symbols": ["IDENTIFICADOR$ebnf$1"]},
    {"name": "STRING$ebnf$1", "symbols": ["TEXTO"]},
    {"name": "STRING$ebnf$1", "symbols": ["STRING$ebnf$1", "TEXTO"], "postprocess": function arrpush(d) {return d[0].concat([d[1]]);}},
    {"name": "STRING", "symbols": ["DCOM", "STRING$ebnf$1", "DCOM"]},
    {"name": "TEXTO", "symbols": ["lenguaje"]},
    {"name": "TEXTO", "symbols": ["digito"]},
    {"name": "TEXTO", "symbols": ["ESP"]},
    {"name": "BOOLEANO$string$1", "symbols": [{"literal":"t"}, {"literal":"r"}, {"literal":"u"}, {"literal":"e"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "BOOLEANO", "symbols": ["BOOLEANO$string$1"]},
    {"name": "BOOLEANO$string$2", "symbols": [{"literal":"f"}, {"literal":"a"}, {"literal":"l"}, {"literal":"s"}, {"literal":"e"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "BOOLEANO", "symbols": ["BOOLEANO$string$2"]},
    {"name": "NUMERO", "symbols": ["digito"]},
    {"name": "NUMERO", "symbols": ["digito", "PUNTO", "digito"]},
    {"name": "FUNCTION$string$1", "symbols": [{"literal":"f"}, {"literal":"u"}, {"literal":"n"}, {"literal":"c"}, {"literal":"t"}, {"literal":"i"}, {"literal":"o"}, {"literal":"n"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "FUNCTION", "symbols": ["FUNCTION$string$1"]},
    {"name": "RETURN$string$1", "symbols": [{"literal":"r"}, {"literal":"e"}, {"literal":"t"}, {"literal":"u"}, {"literal":"r"}, {"literal":"n"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "RETURN", "symbols": ["RETURN$string$1"]},
    {"name": "IF$string$1", "symbols": [{"literal":"i"}, {"literal":"f"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "IF", "symbols": ["IF$string$1"]},
    {"name": "ELSE$string$1", "symbols": [{"literal":"e"}, {"literal":"l"}, {"literal":"s"}, {"literal":"e"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "ELSE", "symbols": ["ELSE$string$1"]},
    {"name": "FOR$string$1", "symbols": [{"literal":"f"}, {"literal":"o"}, {"literal":"r"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "FOR", "symbols": ["FOR$string$1"]},
    {"name": "VAR$string$1", "symbols": [{"literal":"v"}, {"literal":"a"}, {"literal":"r"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "VAR", "symbols": ["VAR$string$1"]},
    {"name": "LET$string$1", "symbols": [{"literal":"l"}, {"literal":"e"}, {"literal":"t"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "LET", "symbols": ["LET$string$1"]},
    {"name": "CONST$string$1", "symbols": [{"literal":"c"}, {"literal":"o"}, {"literal":"n"}, {"literal":"s"}, {"literal":"t"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "CONST", "symbols": ["CONST$string$1"]},
    {"name": "IGUAL", "symbols": [{"literal":"="}]},
    {"name": "APAREN", "symbols": [{"literal":"("}]},
    {"name": "CPAREN", "symbols": [{"literal":")"}]},
    {"name": "ALLAVE", "symbols": [{"literal":"{"}]},
    {"name": "CLLAVE", "symbols": [{"literal":"}"}]},
    {"name": "PUNTO", "symbols": [{"literal":"."}]},
    {"name": "COMA", "symbols": [{"literal":","}]},
    {"name": "DCOM", "symbols": [/["]/]},
    {"name": "PCOMA", "symbols": [{"literal":";"}]},
    {"name": "LOPERADOR$string$1", "symbols": [{"literal":"&"}, {"literal":"&"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "LOPERADOR", "symbols": ["LOPERADOR$string$1"]},
    {"name": "LOPERADOR$string$2", "symbols": [{"literal":"|"}, {"literal":"|"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "LOPERADOR", "symbols": ["LOPERADOR$string$2"]},
    {"name": "LOPERADOR", "symbols": [{"literal":"!"}]},
    {"name": "COPERADOR$string$1", "symbols": [{"literal":"="}, {"literal":"="}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "COPERADOR", "symbols": ["COPERADOR$string$1"]},
    {"name": "COPERADOR$string$2", "symbols": [{"literal":">"}, {"literal":"="}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "COPERADOR", "symbols": ["COPERADOR$string$2"]},
    {"name": "COPERADOR", "symbols": [{"literal":">"}]},
    {"name": "COPERADOR$string$3", "symbols": [{"literal":"<"}, {"literal":"="}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "COPERADOR", "symbols": ["COPERADOR$string$3"]},
    {"name": "COPERADOR", "symbols": [{"literal":"<"}]},
    {"name": "OPERADOR", "symbols": [{"literal":"+"}]},
    {"name": "OPERADOR", "symbols": [{"literal":"-"}]},
    {"name": "OPERADOR", "symbols": [{"literal":"*"}]},
    {"name": "OPERADOR", "symbols": [{"literal":"/"}]},
    {"name": "lenguaje$ebnf$1", "symbols": [/[a-zA-Z_]/]},
    {"name": "lenguaje$ebnf$1", "symbols": ["lenguaje$ebnf$1", /[a-zA-Z_]/], "postprocess": function arrpush(d) {return d[0].concat([d[1]]);}},
    {"name": "lenguaje", "symbols": ["lenguaje$ebnf$1"]},
    {"name": "digito$ebnf$1", "symbols": [/[0-9]/]},
    {"name": "digito$ebnf$1", "symbols": ["digito$ebnf$1", /[0-9]/], "postprocess": function arrpush(d) {return d[0].concat([d[1]]);}},
    {"name": "digito", "symbols": ["digito$ebnf$1"]}
]
  , ParserStart: "programa"
}
if (typeof module !== 'undefined'&& typeof module.exports !== 'undefined') {
   module.exports = grammar;
} else {
   window.grammar = grammar;
}
})();
