// Generated automatically by nearley, version 2.20.1
// http://github.com/Hardmath123/nearley
(function () {
function id(x) { return x[0]; }
var grammar = {
    Lexer: undefined,
    ParserRules: [
    {"name": "input", "symbols": ["funcion"]},
    {"name": "input", "symbols": ["variable"]},
    {"name": "funcion$string$1", "symbols": [{"literal":"f"}, {"literal":"u"}, {"literal":"n"}, {"literal":"c"}, {"literal":"t"}, {"literal":"i"}, {"literal":"o"}, {"literal":"n"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "funcion", "symbols": ["funcion$string$1", {"literal":" "}, "identificador", "propfun", "conLA", "contenido", "conLC"]},
    {"name": "funcion$string$2", "symbols": [{"literal":"c"}, {"literal":"o"}, {"literal":"n"}, {"literal":"s"}, {"literal":"t"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "funcion", "symbols": ["funcion$string$2", {"literal":" "}, "identificador", "conIgual", "propfun", "conD", "conLA", "contenido", "conLC"]},
    {"name": "propfun", "symbols": ["conPA", "parametros"]},
    {"name": "conPC", "symbols": ["conPA", "conPC"]},
    {"name": "contenido", "symbols": ["variable"]},
    {"name": "contenido", "symbols": ["variable", "contenido"]},
    {"name": "contenido", "symbols": ["objeto"]},
    {"name": "contenido", "symbols": ["objeto", "contenido"]},
    {"name": "variable", "symbols": ["tipoDato", {"literal":" "}, "identificador", {"literal":";"}]},
    {"name": "variable", "symbols": ["tipoDato", {"literal":" "}, "identificador", "conIgual", "valor", {"literal":";"}]},
    {"name": "variable", "symbols": ["tipoDato", {"literal":" "}, "identificador", "conIgual", "identificador", "propfun", {"literal":";"}]},
    {"name": "variable", "symbols": ["tipoDato", {"literal":" "}, "identificador", "conIgual", "objeto", {"literal":";"}]},
    {"name": "variable", "symbols": ["identificador", "conIgual", "valor", {"literal":";"}]},
    {"name": "variable", "symbols": ["tipoDato", {"literal":" "}, "identificador", "conIgual", "operacion", {"literal":";"}]},
    {"name": "variable", "symbols": ["identificador", "conIgual", "operacion", {"literal":";"}]},
    {"name": "variable", "symbols": ["identificador", "conIgual", "identificador", "propfun", {"literal":";"}]},
    {"name": "variable", "symbols": ["identificador", "conIgual", "objeto", {"literal":";"}]},
    {"name": "objeto", "symbols": ["propob"]},
    {"name": "objeto", "symbols": ["propob", {"literal":"."}, "propfun"]},
    {"name": "propob", "symbols": ["identificador"]},
    {"name": "propob", "symbols": ["identificador", {"literal":"."}, "objeto"]},
    {"name": "operacion", "symbols": ["valor"]},
    {"name": "operacion", "symbols": ["valor", "conOp", "operacion"]},
    {"name": "operacion", "symbols": ["identificador"]},
    {"name": "operacion", "symbols": ["identificador", "conOp", "operacion"]},
    {"name": "operacion", "symbols": ["conCA", "operacion", "conCC"]},
    {"name": "valor", "symbols": ["numero"]},
    {"name": "valor", "symbols": ["caracter"]},
    {"name": "valor", "symbols": ["string"]},
    {"name": "valor", "symbols": ["booleano"]},
    {"name": "valor", "symbols": ["arreglo"]},
    {"name": "valor", "symbols": []},
    {"name": "arreglo", "symbols": ["conCA", "parametros", "conCC"]},
    {"name": "parametros", "symbols": ["valor"]},
    {"name": "parametros", "symbols": ["identificador"]},
    {"name": "parametros", "symbols": ["objeto"]},
    {"name": "parametros", "symbols": ["valor", "conComa", "parametros"]},
    {"name": "parametros", "symbols": ["objeto", "conComa", "parametros"]},
    {"name": "parametros", "symbols": ["identificador", "conComa", "parametros"]},
    {"name": "numero", "symbols": ["digitos", {"literal":"."}, "digitos"]},
    {"name": "numero", "symbols": ["digitos"]},
    {"name": "identificador", "symbols": ["lenguaje"]},
    {"name": "identificador", "symbols": ["lenguaje", "identificador"]},
    {"name": "identificador", "symbols": ["lenguaje", "identificador", "digitos"]},
    {"name": "conOp", "symbols": ["operadores"]},
    {"name": "conOp", "symbols": [{"literal":" "}, "operadores", {"literal":" "}]},
    {"name": "operadores", "symbols": [{"literal":"+"}]},
    {"name": "operadores", "symbols": [{"literal":"-"}]},
    {"name": "operadores", "symbols": [{"literal":"*"}]},
    {"name": "operadores", "symbols": [{"literal":"/"}]},
    {"name": "operadores", "symbols": [{"literal":">"}]},
    {"name": "operadores", "symbols": [{"literal":"<"}]},
    {"name": "operadores$string$1", "symbols": [{"literal":">"}, {"literal":"="}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "operadores", "symbols": ["operadores$string$1"]},
    {"name": "operadores$string$2", "symbols": [{"literal":"<"}, {"literal":"="}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "operadores", "symbols": ["operadores$string$2"]},
    {"name": "operadores$string$3", "symbols": [{"literal":"="}, {"literal":"="}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "operadores", "symbols": ["operadores$string$3"]},
    {"name": "tipoDato$string$1", "symbols": [{"literal":"v"}, {"literal":"a"}, {"literal":"r"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "tipoDato", "symbols": ["tipoDato$string$1"]},
    {"name": "tipoDato$string$2", "symbols": [{"literal":"l"}, {"literal":"e"}, {"literal":"t"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "tipoDato", "symbols": ["tipoDato$string$2"]},
    {"name": "tipoDato$string$3", "symbols": [{"literal":"c"}, {"literal":"o"}, {"literal":"n"}, {"literal":"s"}, {"literal":"t"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "tipoDato", "symbols": ["tipoDato$string$3"]},
    {"name": "Nulo$string$1", "symbols": [{"literal":"n"}, {"literal":"u"}, {"literal":"l"}, {"literal":"l"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "Nulo", "symbols": ["Nulo$string$1"]},
    {"name": "booleano$string$1", "symbols": [{"literal":"t"}, {"literal":"r"}, {"literal":"u"}, {"literal":"e"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "booleano", "symbols": ["booleano$string$1"]},
    {"name": "booleano$string$2", "symbols": [{"literal":"f"}, {"literal":"a"}, {"literal":"l"}, {"literal":"s"}, {"literal":"e"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "booleano", "symbols": ["booleano$string$2"]},
    {"name": "string", "symbols": [{"literal":"\""}, "caracteres", {"literal":"\""}]},
    {"name": "digitos", "symbols": ["digito"]},
    {"name": "digitos", "symbols": ["digito", "digitos"]},
    {"name": "caracteres", "symbols": ["caracter"]},
    {"name": "caracteres", "symbols": ["caracteres"]},
    {"name": "lenguaje", "symbols": [/[a-zA-Z_]/]},
    {"name": "caracter", "symbols": [/[^\"]/]},
    {"name": "digito", "symbols": [/[0-9]/]},
    {"name": "conIgual", "symbols": [{"literal":"="}]},
    {"name": "conIgual", "symbols": [{"literal":" "}, {"literal":"="}, {"literal":" "}]},
    {"name": "conPA", "symbols": [{"literal":"("}]},
    {"name": "conPA", "symbols": [{"literal":" "}, {"literal":"("}]},
    {"name": "conPA", "symbols": [{"literal":" "}, {"literal":"("}, {"literal":" "}]},
    {"name": "conPC", "symbols": [{"literal":")"}]},
    {"name": "conPC", "symbols": [{"literal":" "}, {"literal":")"}]},
    {"name": "conPC", "symbols": [{"literal":" "}, {"literal":")"}, {"literal":" "}]},
    {"name": "conLA", "symbols": [{"literal":"{"}]},
    {"name": "conLA", "symbols": [{"literal":" "}, {"literal":"{"}]},
    {"name": "conLA", "symbols": [{"literal":" "}, {"literal":"{"}, {"literal":" "}]},
    {"name": "conLC", "symbols": [{"literal":"}"}]},
    {"name": "conLC", "symbols": [{"literal":" "}, {"literal":"}"}]},
    {"name": "conLC", "symbols": [{"literal":" "}, {"literal":"}"}, {"literal":" "}]},
    {"name": "conCA", "symbols": [{"literal":"["}]},
    {"name": "conCA", "symbols": [{"literal":" "}, {"literal":"["}]},
    {"name": "conCA", "symbols": [{"literal":" "}, {"literal":"["}, {"literal":" "}]},
    {"name": "conCC", "symbols": [{"literal":"]"}]},
    {"name": "conCC", "symbols": [{"literal":" "}, {"literal":"]"}]},
    {"name": "conCC", "symbols": [{"literal":" "}, {"literal":"]"}, {"literal":" "}]},
    {"name": "conComa", "symbols": [{"literal":","}]},
    {"name": "conComa", "symbols": [{"literal":","}, {"literal":" "}]},
    {"name": "conD$string$1", "symbols": [{"literal":"="}, {"literal":">"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "conD", "symbols": ["conD$string$1"]},
    {"name": "conD$string$2", "symbols": [{"literal":"="}, {"literal":">"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "conD", "symbols": ["conD$string$2", {"literal":" "}]},
    {"name": "conD$string$3", "symbols": [{"literal":"="}, {"literal":">"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "conD", "symbols": [{"literal":" "}, "conD$string$3"]},
    {"name": "conD$string$4", "symbols": [{"literal":"="}, {"literal":">"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "conD", "symbols": [{"literal":" "}, "conD$string$4", {"literal":" "}]}
]
  , ParserStart: "input"
}
if (typeof module !== 'undefined'&& typeof module.exports !== 'undefined') {
   module.exports = grammar;
} else {
   window.grammar = grammar;
}
})();
